name: Vulkan CI Build

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-query-version: 1.4.321.0
          vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang, SPIRV-Tools
          vulkan-use-cache: true

      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latestrc      # <--= optional, use the latest release candidate (notice the 'rc' suffix).
          ninjaVersion: latest        # <--= optional, use the latest release (non candidate).

      - uses: seanmiddleditch/gha-setup-vsdevenv@v4
        if: runner.os == 'Windows'

      - name: Configure CMake (Windows)
        if: matrix.os == 'windows-latest'
        run: cmake -B build -G "Ninja Multi-Config" -DCMAKE_C_COMPILER=cl.exe -DCMAKE_CXX_COMPILER=cl.exe

      - name: Configure CMake (Non-Windows)
        if: matrix.os != 'windows-latest'
        run: cmake -B build -G "Ninja Multi-Config"

      - name: Build Release
        run: cmake --build build --config Release

      - name: Install Release 
        run: cmake --install build --config Release --component engine

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: engine-${{ matrix.os }}
          path: export/

